name: Test
on: push

jobs:
  check-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.3

      - name: Install tools
        run: |
        python -m pip install --upgrade pip pytest
        pip install openai

      - name: Test with unittest
        run: python3 -m unittest test.py
